### ISSUE TITLE
Build errors on aarch64-apple-darwin

### ISSUE THREAD

**Issue by aspenluxxxy** [BurntSushi/aho-corasick#76]
The issue seems to have been introduced in https://github.com/BurntSushi/aho-corasick/commit/45a4ee770e45805bd79d391031eacc846262a645.

```
aho-corasick on  HEAD (3852632) is 📦 v0.7.15 via 🦀 v1.51.0
❯ git checkout 45a4ee770e45805bd79d391031eacc846262a645
Previous HEAD position was 3852632 0.7.15
HEAD is now at 45a4ee7 edition: run 'cargo fix --edition --all'

aho-corasick on  HEAD (45a4ee7) is 📦 v0.7.15 via 🦀 v1.51.0
❯ cargo check --target aarch64-apple-darwin
    Updating crates.io index
    Checking aho-corasick v0.7.15 (/Users/aspen/Downloads/aho-corasick)
error[E0433]: failed to resolve: use of undeclared crate or module `packed`
 --> src/packed/teddy/mod.rs:4:9
  |
4 | pub use packed::teddy::fallback::Builder;
  |         ^^^^^^ use of undeclared crate or module `packed`

error[E0433]: failed to resolve: use of undeclared crate or module `packed`
 --> src/packed/teddy/mod.rs:6:9
  |
6 | pub use packed::teddy::fallback::Teddy;
  |         ^^^^^^ use of undeclared crate or module `packed`

error[E0433]: failed to resolve: use of undeclared crate or module `packed`
  --> src/packed/teddy/mod.rs:17:9
   |
17 |     use packed::pattern::Patterns;
   |         ^^^^^^ use of undeclared crate or module `packed`

error[E0432]: unresolved import `Match`
  --> src/packed/teddy/mod.rs:18:9
   |
18 |     use Match;
   |         ^^^^^ no external crate `Match`

error[E0432]: unresolved import `crate::packed::teddy::Teddy`
 --> src/packed/api.rs:5:34
  |
5 | use crate::packed::teddy::{self, Teddy};
  |                                  ^^^^^ no `Teddy` in `packed::teddy`

error[E0433]: failed to resolve: could not find `Builder` in `teddy`
   --> src/packed/api.rs:280:16
    |
280 |         teddy::Builder::new()
    |                ^^^^^^^ not found in `teddy`
    |
help: consider importing one of these items
    |
1   | use crate::dfa::Builder;
    |
1   | use crate::nfa::Builder;
    |
1   | use crate::packed::Builder;
    |
1   | use crate::prefilter::Builder;
    |
      and 1 other candidate

error[E0412]: cannot find type `Patterns` in this scope
  --> src/packed/teddy/mod.rs:28:33
   |
28 |         pub fn build(&self, _: &Patterns) -> Option<Teddy> {
   |                                 ^^^^^^^^ not found in this scope
   |
help: consider importing this struct
   |
17 |     use crate::packed::pattern::Patterns;
   |

error[E0412]: cannot find type `Patterns` in this scope
  --> src/packed/teddy/mod.rs:47:17
   |
47 |             _: &Patterns,
   |                 ^^^^^^^^ not found in this scope
   |
help: consider importing this struct
   |
17 |     use crate::packed::pattern::Patterns;
   |

error: aborting due to 8 previous errors

Some errors have detailed explanations: E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `aho-corasick`

To learn more, run the command again with --verbose.
```

**Comment by BurntSushi** [comment]
Yeah, that should already be fixed in https://github.com/BurntSushi/aho-corasick/commit/8ac8f73a2db13edc0cd3cbc4cb0dc9129ff5e8c3. I yanked `0.7.16` and published `0.7.17` with the fix.

**Comment by aspenluxxxy** [comment]
That seems to have fixed it - the crates.io index must've not been updated whenever I was testing this. Thanks!

**Comment by BurntSushi** [comment]
Ah interesting. Minor clarification: it was `0.7.17` that was broken and what I yanked. (I also yanked `0.7.16` due to a release snafu. Sigh.) It is `0.7.18` that has the fix. I've edited my previous comment to reflect that.

Thanks for reporting this! I wonder if this target is supported in GitHub Actions yet.

**Comment by aspenluxxxy** [comment]
the Big Sur environments in Actions can cross-compile to it, last I checked.
