### ISSUE TITLE
Build failure using Rustc 1.28.0-1.39.0 because of cfg(doctest)

### ISSUE THREAD

**Issue by iliekturtles** [BurntSushi/aho-corasick#62]
https://github.com/BurntSushi/aho-corasick/commit/933b6a71aedc6d2a3c399f250a2ff30479407328, released as part of v0.7.11, includes `cfg(doctest)` which isn't stabilized until [Rust 1.40.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#misc-3). I get a build failure in `uom` using Rust 1.38.0 running [`cargo clippy --all --tests`](https://travis-ci.org/github/iliekturtles/uom/jobs/701002594#L277). Based on the [MSRV](https://github.com/BurntSushi/aho-corasick#minimum-rust-version-policy) I would expect this to still work with 1.38.0.

Reproduced locally:
```
$ RUSTFLAGS="-D warnings" cargo +1.38.0 clippy --all --tests
    Checking aho-corasick v0.7.12
    Checking num-traits v0.2.12
    Checking serde_json v1.0.55
error[E0658]: `cfg(doctest)` is experimental and subject to change
   --> C:\Users\mjboutin\.local\share\cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.12\src\lib.rs:190:7
    |
190 | #[cfg(doctest)]
    |       ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62210

error[E0658]: `cfg(doctest)` is experimental and subject to change
   --> C:\Users\mjboutin\.local\share\cargo\registry\src\github.com-1ecc6299db9ec823\aho-corasick-0.7.12\src\lib.rs:194:7
    |
194 | #[cfg(doctest)]
    |       ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62210

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `aho-corasick`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ghedo** [comment]
Same here https://travis-ci.com/github/cloudflare/quiche/jobs/352612989

**Comment by BurntSushi** [comment]
Yeah, the same issue happened with regex: https://github.com/rust-lang/regex/commit/d7fbd158f7e62e9319fcc254bde43b954511a669

Basically, `cfg(doctest)` doesn't cause build failures on Rust 1.28 (the MSRV), but does on Rust 1.39. So that's why this change made it past CI. I've disabled the use of `doc_comment` for now (which sadly requires an MSRV of Rust 1.43).

**Comment by iliekturtles** [comment]
Thanks @BurntSushi, success with the latest version: https://travis-ci.org/github/iliekturtles/uom/jobs/701026167
